openapi: 3.0.0
info:
  version: 0.1.0
  title: Persona Client API
  termsOfService: 'https://persona.eniehack.net/tos'
  contact:
    email: eniehack@outlook.jp
  license:
    name: AGPL 3.0
    url: 'https://www.gnu.org/licenses/agpl-3.0.html'
  x-logo:
    url: 'https://apis.guru/openapi-template/logo.png'
  description: >
    [Persona-Server](https://github.com/eniehack/persona-server)で実装されている、もしくは今後実装される予定のAPIを記述するドキュメントです。


    APIのバージョンとPersona-Serverのバージョンはリンクしています。

    つまり、Persona-Serverがv0.1.0となったとき、API v0.1.0を実装完了するということです。


    改善点等見つけられましたら[issue](https://github.com/persona-dev/c2s-api-spec/issues/new)までお願いします。

    ## Paseto tokenについて

    Personaでは認証認可を[Paseto](https://paseto.io)を用いて行います。
externalDocs:
  description: Find out how to create Github repo for your OpenAPI spec.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Accounts
    description: 'Operations about accounts. ex)login, signup, account settings.'
  - name: Posts
    description: Operations about posts.
  - name: Administration
    description: Operation about Administration and Moderation.
servers:
  - url: 'https://persona.eniehack.net/api/v1'
